# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chamber.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/5e_logo_dark_256.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wgt_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.wgt_tab.setGeometry(QtCore.QRect(10, 10, 761, 541))
        self.wgt_tab.setObjectName("wgt_tab")
        self.tab_chamber = QtWidgets.QWidget()
        self.tab_chamber.setObjectName("tab_chamber")
        self.btn_rr_Odor = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Odor.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.btn_rr_Odor.setObjectName("btn_rr_Odor")
        self.lck_Feature_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Feature_2.setGeometry(QtCore.QRect(20, 330, 16, 18))
        self.lck_Feature_2.setText("")
        self.lck_Feature_2.setObjectName("lck_Feature_2")
        self.txt_Feature_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Feature_2.setGeometry(QtCore.QRect(50, 330, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_2.sizePolicy().hasHeightForWidth())
        self.txt_Feature_2.setSizePolicy(sizePolicy)
        self.txt_Feature_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_2.setObjectName("txt_Feature_2")
        self.btn_rr_Furnish_Utensil = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Furnish_Utensil.setGeometry(QtCore.QRect(240, 260, 71, 21))
        self.btn_rr_Furnish_Utensil.setObjectName("btn_rr_Furnish_Utensil")
        self.lck_Furnish_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_1.setGeometry(QtCore.QRect(20, 430, 16, 18))
        self.lck_Furnish_1.setText("")
        self.lck_Furnish_1.setObjectName("lck_Furnish_1")
        self.txt_Furnish_Religous_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Religous_1.setGeometry(QtCore.QRect(390, 430, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_1.setObjectName("txt_Furnish_Religous_1")
        self.txt_Odor = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Odor.setGeometry(QtCore.QRect(190, 170, 211, 21))
        self.txt_Odor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Odor.setObjectName("txt_Odor")
        self.lck_Furnish_Mage_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Mage_3.setGeometry(QtCore.QRect(190, 490, 16, 18))
        self.lck_Furnish_Mage_3.setText("")
        self.lck_Furnish_Mage_3.setObjectName("lck_Furnish_Mage_3")
        self.txt_Feature_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Feature_1.setGeometry(QtCore.QRect(50, 300, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_1.sizePolicy().hasHeightForWidth())
        self.txt_Feature_1.setSizePolicy(sizePolicy)
        self.txt_Feature_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_1.setObjectName("txt_Feature_1")
        self.lck_Feature_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Feature_1.setGeometry(QtCore.QRect(20, 300, 16, 18))
        self.lck_Feature_1.setText("")
        self.lck_Feature_1.setObjectName("lck_Feature_1")
        self.txt_Container_Contents_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Container_Contents_1.setGeometry(QtCore.QRect(560, 300, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_1.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_1.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_1.setObjectName("txt_Container_Contents_1")
        self.btn_rr_Feature = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Feature.setGeometry(QtCore.QRect(70, 260, 71, 21))
        self.btn_rr_Feature.setObjectName("btn_rr_Feature")
        self.btn_rr_Furnish_Mage = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Furnish_Mage.setGeometry(QtCore.QRect(240, 390, 71, 21))
        self.btn_rr_Furnish_Mage.setObjectName("btn_rr_Furnish_Mage")
        self.lbl_Environment = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Environment.setGeometry(QtCore.QRect(110, 80, 71, 16))
        self.lbl_Environment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Environment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Environment.setObjectName("lbl_Environment")
        self.lck_Furnish_Utensil_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Utensil_3.setGeometry(QtCore.QRect(190, 360, 16, 18))
        self.lck_Furnish_Utensil_3.setText("")
        self.lck_Furnish_Utensil_3.setObjectName("lck_Furnish_Utensil_3")
        self.txt_Noise = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Noise.setGeometry(QtCore.QRect(190, 110, 211, 21))
        self.txt_Noise.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Noise.setObjectName("txt_Noise")
        self.btn_rr_Container_Contents = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Container_Contents.setGeometry(QtCore.QRect(580, 260, 71, 21))
        self.btn_rr_Container_Contents.setObjectName("btn_rr_Container_Contents")
        self.txt_Furnish_Utensil_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Utensil_3.setGeometry(QtCore.QRect(220, 360, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_3.setObjectName("txt_Furnish_Utensil_3")
        self.txt_Furnish_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_1.setGeometry(QtCore.QRect(50, 430, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_1.setObjectName("txt_Furnish_1")
        self.txt_Furnish_Religous_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Religous_3.setGeometry(QtCore.QRect(390, 490, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_3.setObjectName("txt_Furnish_Religous_3")
        self.txt_Furnish_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_2.setGeometry(QtCore.QRect(50, 460, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_2.setObjectName("txt_Furnish_2")
        self.lck_Container_Contents_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Container_Contents_2.setGeometry(QtCore.QRect(530, 330, 16, 18))
        self.lck_Container_Contents_2.setText("")
        self.lck_Container_Contents_2.setObjectName("lck_Container_Contents_2")
        self.lck_Furnish_Mage_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Mage_2.setGeometry(QtCore.QRect(190, 460, 16, 18))
        self.lck_Furnish_Mage_2.setText("")
        self.lck_Furnish_Mage_2.setObjectName("lck_Furnish_Mage_2")
        self.lck_DungeonType = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_DungeonType.setGeometry(QtCore.QRect(100, 50, 16, 18))
        self.lck_DungeonType.setText("")
        self.lck_DungeonType.setObjectName("lck_DungeonType")
        self.lck_Furnish_Religous_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Religous_1.setGeometry(QtCore.QRect(360, 430, 16, 18))
        self.lck_Furnish_Religous_1.setText("")
        self.lck_Furnish_Religous_1.setObjectName("lck_Furnish_Religous_1")
        self.lbl_Furnish_Utensil = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Furnish_Utensil.setGeometry(QtCore.QRect(230, 280, 101, 16))
        self.lbl_Furnish_Utensil.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Utensil.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Utensil.setObjectName("lbl_Furnish_Utensil")
        self.lck_Book_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Book_2.setGeometry(QtCore.QRect(360, 330, 16, 18))
        self.lck_Book_2.setText("")
        self.lck_Book_2.setObjectName("lck_Book_2")
        self.lck_Feature_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Feature_3.setGeometry(QtCore.QRect(20, 360, 16, 18))
        self.lck_Feature_3.setText("")
        self.lck_Feature_3.setObjectName("lck_Feature_3")
        self.txt_Furnish_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_3.setGeometry(QtCore.QRect(50, 490, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_3.setObjectName("txt_Furnish_3")
        self.lbl_Locked_2 = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Locked_2.setGeometry(QtCore.QRect(4, 280, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked_2.setFont(font)
        self.lbl_Locked_2.setObjectName("lbl_Locked_2")
        self.lbl_Furnish = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Furnish.setGeometry(QtCore.QRect(70, 410, 71, 16))
        self.lbl_Furnish.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish.setObjectName("lbl_Furnish")
        self.txt_Book_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Book_3.setGeometry(QtCore.QRect(390, 360, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_3.sizePolicy().hasHeightForWidth())
        self.txt_Book_3.setSizePolicy(sizePolicy)
        self.txt_Book_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_3.setObjectName("txt_Book_3")
        self.txt_Furnish_Utensil_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Utensil_2.setGeometry(QtCore.QRect(220, 330, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_2.setObjectName("txt_Furnish_Utensil_2")
        self.lbl_Container_Contents = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Container_Contents.setGeometry(QtCore.QRect(570, 280, 101, 16))
        self.lbl_Container_Contents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Container_Contents.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Container_Contents.setObjectName("lbl_Container_Contents")
        self.lck_Furnish_Religous_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Religous_2.setGeometry(QtCore.QRect(360, 460, 16, 18))
        self.lck_Furnish_Religous_2.setText("")
        self.lck_Furnish_Religous_2.setObjectName("lck_Furnish_Religous_2")
        self.lck_Air = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Air.setGeometry(QtCore.QRect(100, 140, 16, 18))
        self.lck_Air.setText("")
        self.lck_Air.setObjectName("lck_Air")
        self.txt_Furnish_Mage_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Mage_1.setGeometry(QtCore.QRect(220, 430, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_1.setObjectName("txt_Furnish_Mage_1")
        self.txt_Container_Contents_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Container_Contents_2.setGeometry(QtCore.QRect(560, 330, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_2.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_2.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_2.setObjectName("txt_Container_Contents_2")
        self.btn_rr_Noise = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Noise.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.btn_rr_Noise.setObjectName("btn_rr_Noise")
        self.btn_rr_Environment = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Environment.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.btn_rr_Environment.setObjectName("btn_rr_Environment")
        self.lbl_Furnish_Mage = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Furnish_Mage.setGeometry(QtCore.QRect(230, 410, 101, 16))
        self.lbl_Furnish_Mage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Mage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Mage.setObjectName("lbl_Furnish_Mage")
        self.lck_Furnish_Utensil_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Utensil_2.setGeometry(QtCore.QRect(190, 330, 16, 18))
        self.lck_Furnish_Utensil_2.setText("")
        self.lck_Furnish_Utensil_2.setObjectName("lck_Furnish_Utensil_2")
        self.lck_Furnish_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_3.setGeometry(QtCore.QRect(20, 490, 16, 18))
        self.lck_Furnish_3.setText("")
        self.lck_Furnish_3.setObjectName("lck_Furnish_3")
        self.lbl_Odor = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Odor.setGeometry(QtCore.QRect(130, 170, 51, 20))
        self.lbl_Odor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Odor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Odor.setObjectName("lbl_Odor")
        self.lck_Container_Contents_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Container_Contents_1.setGeometry(QtCore.QRect(530, 300, 16, 18))
        self.lck_Container_Contents_1.setText("")
        self.lck_Container_Contents_1.setObjectName("lck_Container_Contents_1")
        self.lbl_Locked = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Locked.setGeometry(QtCore.QRect(83, 30, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked.setFont(font)
        self.lbl_Locked.setObjectName("lbl_Locked")
        self.btn_rr_Air = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Air.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.btn_rr_Air.setObjectName("btn_rr_Air")
        self.lbl_Features = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Features.setGeometry(QtCore.QRect(70, 280, 71, 16))
        self.lbl_Features.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Features.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Features.setObjectName("lbl_Features")
        self.lbl_Furnish_Religous = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Furnish_Religous.setGeometry(QtCore.QRect(400, 410, 101, 16))
        self.lbl_Furnish_Religous.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Religous.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Religous.setObjectName("lbl_Furnish_Religous")
        self.txt_Book_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Book_2.setGeometry(QtCore.QRect(390, 330, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_2.sizePolicy().hasHeightForWidth())
        self.txt_Book_2.setSizePolicy(sizePolicy)
        self.txt_Book_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_2.setObjectName("txt_Book_2")
        self.cb_Environment = QtWidgets.QComboBox(self.tab_chamber)
        self.cb_Environment.setGeometry(QtCore.QRect(190, 80, 91, 22))
        self.cb_Environment.setObjectName("cb_Environment")
        self.lck_Container_Contents_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Container_Contents_3.setGeometry(QtCore.QRect(530, 360, 16, 18))
        self.lck_Container_Contents_3.setText("")
        self.lck_Container_Contents_3.setObjectName("lck_Container_Contents_3")
        self.txt_Air = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Air.setGeometry(QtCore.QRect(190, 140, 211, 21))
        self.txt_Air.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Air.setObjectName("txt_Air")
        self.txt_Furnish_Mage_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Mage_3.setGeometry(QtCore.QRect(220, 490, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_3.setObjectName("txt_Furnish_Mage_3")
        self.lbl_Book = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Book.setGeometry(QtCore.QRect(410, 280, 71, 16))
        self.lbl_Book.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Book.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Book.setObjectName("lbl_Book")
        self.btn_rr_Book = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Book.setGeometry(QtCore.QRect(410, 260, 71, 21))
        self.btn_rr_Book.setObjectName("btn_rr_Book")
        self.btn_rr_DungeonType = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_DungeonType.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.btn_rr_DungeonType.setObjectName("btn_rr_DungeonType")
        self.lck_Book_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Book_3.setGeometry(QtCore.QRect(360, 360, 16, 18))
        self.lck_Book_3.setText("")
        self.lck_Book_3.setObjectName("lck_Book_3")
        self.txt_Furnish_Mage_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Mage_2.setGeometry(QtCore.QRect(220, 460, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_2.setObjectName("txt_Furnish_Mage_2")
        self.lck_Furnish_Religous_3 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Religous_3.setGeometry(QtCore.QRect(360, 490, 16, 18))
        self.lck_Furnish_Religous_3.setText("")
        self.lck_Furnish_Religous_3.setObjectName("lck_Furnish_Religous_3")
        self.txt_Container_Contents_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Container_Contents_3.setGeometry(QtCore.QRect(560, 360, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_3.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_3.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_3.setObjectName("txt_Container_Contents_3")
        self.txt_Feature_3 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Feature_3.setGeometry(QtCore.QRect(50, 360, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_3.sizePolicy().hasHeightForWidth())
        self.txt_Feature_3.setSizePolicy(sizePolicy)
        self.txt_Feature_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_3.setObjectName("txt_Feature_3")
        self.lck_Noise = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Noise.setGeometry(QtCore.QRect(100, 110, 16, 18))
        self.lck_Noise.setText("")
        self.lck_Noise.setObjectName("lck_Noise")
        self.lbl_DungeonType = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_DungeonType.setGeometry(QtCore.QRect(150, 50, 31, 16))
        self.lbl_DungeonType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_DungeonType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_DungeonType.setObjectName("lbl_DungeonType")
        self.txt_Furnish_Religous_2 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Religous_2.setGeometry(QtCore.QRect(390, 460, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_2.setObjectName("txt_Furnish_Religous_2")
        self.lck_Odor = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Odor.setGeometry(QtCore.QRect(100, 170, 16, 18))
        self.lck_Odor.setText("")
        self.lck_Odor.setObjectName("lck_Odor")
        self.txt_Furnish_Utensil_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Furnish_Utensil_1.setGeometry(QtCore.QRect(220, 300, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_1.setObjectName("txt_Furnish_Utensil_1")
        self.txt_Book_1 = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Book_1.setGeometry(QtCore.QRect(390, 300, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_1.sizePolicy().hasHeightForWidth())
        self.txt_Book_1.setSizePolicy(sizePolicy)
        self.txt_Book_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_1.setObjectName("txt_Book_1")
        self.lck_Furnish_2 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_2.setGeometry(QtCore.QRect(20, 460, 16, 18))
        self.lck_Furnish_2.setText("")
        self.lck_Furnish_2.setObjectName("lck_Furnish_2")
        self.btn_all_rr = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_all_rr.setGeometry(QtCore.QRect(310, 10, 131, 31))
        self.btn_all_rr.setObjectName("btn_all_rr")
        self.lbl_Noise = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Noise.setGeometry(QtCore.QRect(130, 110, 51, 20))
        self.lbl_Noise.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Noise.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Noise.setObjectName("lbl_Noise")
        self.lck_Environment = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Environment.setGeometry(QtCore.QRect(100, 80, 16, 18))
        self.lck_Environment.setText("")
        self.lck_Environment.setObjectName("lck_Environment")
        self.lck_Book_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Book_1.setGeometry(QtCore.QRect(360, 300, 16, 18))
        self.lck_Book_1.setText("")
        self.lck_Book_1.setObjectName("lck_Book_1")
        self.lbl_Air = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Air.setGeometry(QtCore.QRect(130, 140, 51, 20))
        self.lbl_Air.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Air.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Air.setObjectName("lbl_Air")
        self.lck_Furnish_Utensil_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Utensil_1.setGeometry(QtCore.QRect(190, 300, 16, 18))
        self.lck_Furnish_Utensil_1.setText("")
        self.lck_Furnish_Utensil_1.setObjectName("lck_Furnish_Utensil_1")
        self.lck_Furnish_Mage_1 = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Furnish_Mage_1.setGeometry(QtCore.QRect(190, 430, 16, 18))
        self.lck_Furnish_Mage_1.setText("")
        self.lck_Furnish_Mage_1.setObjectName("lck_Furnish_Mage_1")
        self.btn_rr_Furnish = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Furnish.setGeometry(QtCore.QRect(70, 390, 71, 21))
        self.btn_rr_Furnish.setObjectName("btn_rr_Furnish")
        self.btn_rr_Furnish_Religous = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Furnish_Religous.setGeometry(QtCore.QRect(410, 390, 71, 21))
        self.btn_rr_Furnish_Religous.setObjectName("btn_rr_Furnish_Religous")
        self.cb_DungeonType = QtWidgets.QComboBox(self.tab_chamber)
        self.cb_DungeonType.setGeometry(QtCore.QRect(190, 50, 91, 22))
        self.cb_DungeonType.setObjectName("cb_DungeonType")
        self.btn_rr_ChamSize = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_ChamSize.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.btn_rr_ChamSize.setObjectName("btn_rr_ChamSize")
        self.lbl_ChamSize = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_ChamSize.setGeometry(QtCore.QRect(120, 200, 61, 20))
        self.lbl_ChamSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ChamSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_ChamSize.setObjectName("lbl_ChamSize")
        self.txt_ChamSize = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_ChamSize.setGeometry(QtCore.QRect(190, 200, 211, 21))
        self.txt_ChamSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_ChamSize.setObjectName("txt_ChamSize")
        self.lck_ChamSize = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_ChamSize.setGeometry(QtCore.QRect(100, 200, 16, 18))
        self.lck_ChamSize.setText("")
        self.lck_ChamSize.setObjectName("lck_ChamSize")
        self.lbl_ChamPurpose = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_ChamPurpose.setGeometry(QtCore.QRect(130, 230, 51, 20))
        self.lbl_ChamPurpose.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ChamPurpose.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_ChamPurpose.setObjectName("lbl_ChamPurpose")
        self.txt_ChamPurpose = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_ChamPurpose.setGeometry(QtCore.QRect(190, 230, 211, 21))
        self.txt_ChamPurpose.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_ChamPurpose.setObjectName("txt_ChamPurpose")
        self.btn_rr_ChamPurpose = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_ChamPurpose.setGeometry(QtCore.QRect(10, 230, 71, 21))
        self.btn_rr_ChamPurpose.setObjectName("btn_rr_ChamPurpose")
        self.lck_ChamPurpose = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_ChamPurpose.setGeometry(QtCore.QRect(100, 230, 16, 18))
        self.lck_ChamPurpose.setText("")
        self.lck_ChamPurpose.setObjectName("lck_ChamPurpose")
        self.btn_rr_ChamHazard = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_ChamHazard.setGeometry(QtCore.QRect(490, 20, 71, 21))
        self.btn_rr_ChamHazard.setObjectName("btn_rr_ChamHazard")
        self.txt_ChamHazard = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_ChamHazard.setGeometry(QtCore.QRect(490, 50, 221, 21))
        self.txt_ChamHazard.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_ChamHazard.setObjectName("txt_ChamHazard")
        self.lbl_ChamHazard = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_ChamHazard.setGeometry(QtCore.QRect(590, 20, 51, 20))
        self.lbl_ChamHazard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ChamHazard.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ChamHazard.setObjectName("lbl_ChamHazard")
        self.lck_ChamHazard = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_ChamHazard.setGeometry(QtCore.QRect(570, 20, 16, 18))
        self.lck_ChamHazard.setText("")
        self.lck_ChamHazard.setObjectName("lck_ChamHazard")
        self.txt_Trap = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Trap.setGeometry(QtCore.QRect(490, 110, 221, 51))
        self.txt_Trap.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Trap.setObjectName("txt_Trap")
        self.lbl_Trap = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Trap.setGeometry(QtCore.QRect(590, 80, 51, 20))
        self.lbl_Trap.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Trap.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Trap.setObjectName("lbl_Trap")
        self.btn_rr_Trap = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Trap.setGeometry(QtCore.QRect(490, 80, 71, 21))
        self.btn_rr_Trap.setObjectName("btn_rr_Trap")
        self.lck_Trap = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Trap.setGeometry(QtCore.QRect(570, 80, 16, 18))
        self.lck_Trap.setText("")
        self.lck_Trap.setObjectName("lck_Trap")
        self.btn_rr_Trick = QtWidgets.QPushButton(self.tab_chamber)
        self.btn_rr_Trick.setGeometry(QtCore.QRect(490, 170, 71, 21))
        self.btn_rr_Trick.setObjectName("btn_rr_Trick")
        self.lck_Trick = QtWidgets.QCheckBox(self.tab_chamber)
        self.lck_Trick.setGeometry(QtCore.QRect(570, 170, 16, 18))
        self.lck_Trick.setText("")
        self.lck_Trick.setObjectName("lck_Trick")
        self.lbl_Trick = QtWidgets.QLabel(self.tab_chamber)
        self.lbl_Trick.setGeometry(QtCore.QRect(590, 170, 51, 20))
        self.lbl_Trick.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Trick.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_Trick.setObjectName("lbl_Trick")
        self.txt_Trick = QtWidgets.QPlainTextEdit(self.tab_chamber)
        self.txt_Trick.setGeometry(QtCore.QRect(490, 200, 221, 51))
        self.txt_Trick.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Trick.setObjectName("txt_Trick")
        self.wgt_tab.addTab(self.tab_chamber, "")
        self.tab_mob = QtWidgets.QWidget()
        self.tab_mob.setObjectName("tab_mob")
        self.pushButton = QtWidgets.QPushButton(self.tab_mob)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.lbl_MobName = QtWidgets.QLabel(self.tab_mob)
        self.lbl_MobName.setGeometry(QtCore.QRect(50, 70, 41, 20))
        self.lbl_MobName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_MobName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MobName.setObjectName("lbl_MobName")
        self.txt_MobName = QtWidgets.QPlainTextEdit(self.tab_mob)
        self.txt_MobName.setGeometry(QtCore.QRect(100, 70, 211, 21))
        self.txt_MobName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_MobName.setObjectName("txt_MobName")
        self.lck_MobName = QtWidgets.QCheckBox(self.tab_mob)
        self.lck_MobName.setGeometry(QtCore.QRect(30, 70, 16, 18))
        self.lck_MobName.setText("")
        self.lck_MobName.setObjectName("lck_MobName")
        self.lbl_MobType = QtWidgets.QLabel(self.tab_mob)
        self.lbl_MobType.setGeometry(QtCore.QRect(50, 100, 41, 20))
        self.lbl_MobType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_MobType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_MobType.setObjectName("lbl_MobType")
        self.txt_MobType = QtWidgets.QPlainTextEdit(self.tab_mob)
        self.txt_MobType.setGeometry(QtCore.QRect(100, 100, 211, 21))
        self.txt_MobType.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_MobType.setObjectName("txt_MobType")
        self.lck_MobType = QtWidgets.QCheckBox(self.tab_mob)
        self.lck_MobType.setGeometry(QtCore.QRect(30, 100, 16, 18))
        self.lck_MobType.setText("")
        self.lck_MobType.setObjectName("lck_MobType")
        self.wgt_tab.addTab(self.tab_mob, "")
        self.tab_notes = QtWidgets.QWidget()
        self.tab_notes.setObjectName("tab_notes")
        self.textEdit = QtWidgets.QTextEdit(self.tab_notes)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 701, 421))
        self.textEdit.setObjectName("textEdit")
        self.wgt_tab.addTab(self.tab_notes, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChamber = QtWidgets.QAction(MainWindow)
        self.actionChamber.setObjectName("actionChamber")
        self.actionPassage = QtWidgets.QAction(MainWindow)
        self.actionPassage.setObjectName("actionPassage")
        self.actionDoor = QtWidgets.QAction(MainWindow)
        self.actionDoor.setObjectName("actionDoor")
        self.actionEntrance = QtWidgets.QAction(MainWindow)
        self.actionEntrance.setObjectName("actionEntrance")
        self.actionMonster = QtWidgets.QAction(MainWindow)
        self.actionMonster.setObjectName("actionMonster")
        self.actionNPC = QtWidgets.QAction(MainWindow)
        self.actionNPC.setObjectName("actionNPC")
        self.actionPlayer = QtWidgets.QAction(MainWindow)
        self.actionPlayer.setObjectName("actionPlayer")
        self.actionCity = QtWidgets.QAction(MainWindow)
        self.actionCity.setObjectName("actionCity")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionRoll_Tables = QtWidgets.QAction(MainWindow)
        self.actionRoll_Tables.setObjectName("actionRoll_Tables")

        self.retranslateUi(MainWindow)
        self.wgt_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Random Session Maker"))
        self.btn_rr_Odor.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Furnish_Utensil.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Feature.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Furnish_Mage.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Environment.setText(_translate("MainWindow", "Environment:"))
        self.btn_rr_Container_Contents.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Furnish_Utensil.setText(_translate("MainWindow", "Utensils / Personal"))
        self.lbl_Locked_2.setText(_translate("MainWindow", "Locked"))
        self.lbl_Furnish.setText(_translate("MainWindow", "Furnishings:"))
        self.lbl_Container_Contents.setText(_translate("MainWindow", "Container Contents"))
        self.btn_rr_Noise.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Environment.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Furnish_Mage.setText(_translate("MainWindow", "Furnishings: Mage"))
        self.lbl_Odor.setText(_translate("MainWindow", "Odor:"))
        self.lbl_Locked.setText(_translate("MainWindow", "Locked"))
        self.btn_rr_Air.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Features.setText(_translate("MainWindow", "Features:"))
        self.lbl_Furnish_Religous.setText(_translate("MainWindow", "Furnishings: Relgious"))
        self.lbl_Book.setText(_translate("MainWindow", "Books / Tomes"))
        self.btn_rr_Book.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_DungeonType.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_DungeonType.setText(_translate("MainWindow", "Type:"))
        self.btn_all_rr.setText(_translate("MainWindow", "Generate Chamber"))
        self.lbl_Noise.setText(_translate("MainWindow", "Noise:"))
        self.lbl_Air.setText(_translate("MainWindow", "Air:"))
        self.btn_rr_Furnish.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Furnish_Religous.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_ChamSize.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_ChamSize.setText(_translate("MainWindow", "Size:"))
        self.lbl_ChamPurpose.setText(_translate("MainWindow", "Purpose:"))
        self.btn_rr_ChamPurpose.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_ChamHazard.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_ChamHazard.setText(_translate("MainWindow", "Hazard:"))
        self.lbl_Trap.setText(_translate("MainWindow", "Trap:"))
        self.btn_rr_Trap.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Trick.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Trick.setText(_translate("MainWindow", "Trick:"))
        self.wgt_tab.setTabText(self.wgt_tab.indexOf(self.tab_chamber), _translate("MainWindow", "Chamber Details"))
        self.pushButton.setText(_translate("MainWindow", "Generate Mob"))
        self.lbl_MobName.setText(_translate("MainWindow", "Name:"))
        self.lbl_MobType.setText(_translate("MainWindow", "Type:"))
        self.wgt_tab.setTabText(self.wgt_tab.indexOf(self.tab_mob), _translate("MainWindow", "Mobs"))
        self.wgt_tab.setTabText(self.wgt_tab.indexOf(self.tab_notes), _translate("MainWindow", "Notes"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionChamber.setText(_translate("MainWindow", "Chamber"))
        self.actionPassage.setText(_translate("MainWindow", "Passage"))
        self.actionDoor.setText(_translate("MainWindow", "Door"))
        self.actionEntrance.setText(_translate("MainWindow", "Entrance"))
        self.actionMonster.setText(_translate("MainWindow", "Monster"))
        self.actionNPC.setText(_translate("MainWindow", "NPC"))
        self.actionPlayer.setText(_translate("MainWindow", "Player"))
        self.actionCity.setText(_translate("MainWindow", "City"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionRoll_Tables.setText(_translate("MainWindow", "Roll Tables"))

import QtResources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

