# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSM_Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 609)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/5e_logo_dark_256.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Header = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Header.setGeometry(QtCore.QRect(0, 15, 261, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Header.setFont(font)
        self.lbl_Header.setObjectName("lbl_Header")
        self.btn_all_rr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_all_rr.setGeometry(QtCore.QRect(270, 10, 131, 31))
        self.btn_all_rr.setObjectName("btn_all_rr")
        self.lbl_DungeonType = QtWidgets.QLabel(self.centralwidget)
        self.lbl_DungeonType.setGeometry(QtCore.QRect(170, 70, 31, 16))
        self.lbl_DungeonType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_DungeonType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_DungeonType.setObjectName("lbl_DungeonType")
        self.cb_DungeonType = QtWidgets.QComboBox(self.centralwidget)
        self.cb_DungeonType.setGeometry(QtCore.QRect(210, 70, 91, 22))
        self.cb_DungeonType.setObjectName("cb_DungeonType")
        self.lck_DungeonType = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_DungeonType.setGeometry(QtCore.QRect(100, 70, 16, 18))
        self.lck_DungeonType.setText("")
        self.lck_DungeonType.setObjectName("lck_DungeonType")
        self.lbl_Locked = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Locked.setGeometry(QtCore.QRect(83, 50, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked.setFont(font)
        self.lbl_Locked.setObjectName("lbl_Locked")
        self.lbl_Environment = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Environment.setGeometry(QtCore.QRect(140, 100, 71, 16))
        self.lbl_Environment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Environment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Environment.setObjectName("lbl_Environment")
        self.lck_Environment = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Environment.setGeometry(QtCore.QRect(100, 100, 16, 18))
        self.lck_Environment.setText("")
        self.lck_Environment.setObjectName("lck_Environment")
        self.cb_Environment = QtWidgets.QComboBox(self.centralwidget)
        self.cb_Environment.setGeometry(QtCore.QRect(210, 100, 91, 22))
        self.cb_Environment.setObjectName("cb_Environment")
        self.lbl_StartArea = QtWidgets.QLabel(self.centralwidget)
        self.lbl_StartArea.setGeometry(QtCore.QRect(130, 140, 71, 16))
        self.lbl_StartArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_StartArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_StartArea.setObjectName("lbl_StartArea")
        self.lck_StartArea = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_StartArea.setGeometry(QtCore.QRect(100, 140, 16, 18))
        self.lck_StartArea.setText("")
        self.lck_StartArea.setObjectName("lck_StartArea")
        self.btn_rr_DungeonType = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_DungeonType.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.btn_rr_DungeonType.setObjectName("btn_rr_DungeonType")
        self.btn_rr_Environment = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Environment.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.btn_rr_Environment.setObjectName("btn_rr_Environment")
        self.btn_rr_StartArea = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_StartArea.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.btn_rr_StartArea.setObjectName("btn_rr_StartArea")
        self.txt_StartArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_StartArea.setGeometry(QtCore.QRect(210, 130, 391, 41))
        self.txt_StartArea.setObjectName("txt_StartArea")
        self.lbl_Noise = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Noise.setGeometry(QtCore.QRect(130, 180, 71, 16))
        self.lbl_Noise.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Noise.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Noise.setObjectName("lbl_Noise")
        self.btn_rr_Noise = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Noise.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.btn_rr_Noise.setObjectName("btn_rr_Noise")
        self.lck_Noise = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Noise.setGeometry(QtCore.QRect(100, 180, 16, 18))
        self.lck_Noise.setText("")
        self.lck_Noise.setObjectName("lck_Noise")
        self.txt_Noise = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Noise.setGeometry(QtCore.QRect(210, 180, 211, 21))
        self.txt_Noise.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Noise.setObjectName("txt_Noise")
        self.lbl_Air = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Air.setGeometry(QtCore.QRect(130, 210, 71, 16))
        self.lbl_Air.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Air.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Air.setObjectName("lbl_Air")
        self.btn_rr_Air = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Air.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.btn_rr_Air.setObjectName("btn_rr_Air")
        self.lck_Air = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Air.setGeometry(QtCore.QRect(100, 210, 16, 18))
        self.lck_Air.setText("")
        self.lck_Air.setObjectName("lck_Air")
        self.txt_Air = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Air.setGeometry(QtCore.QRect(210, 210, 211, 21))
        self.txt_Air.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Air.setObjectName("txt_Air")
        self.lbl_Odor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Odor.setGeometry(QtCore.QRect(130, 240, 71, 16))
        self.lbl_Odor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Odor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Odor.setObjectName("lbl_Odor")
        self.txt_Odor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Odor.setGeometry(QtCore.QRect(210, 240, 211, 21))
        self.txt_Odor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Odor.setObjectName("txt_Odor")
        self.lck_Odor = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Odor.setGeometry(QtCore.QRect(100, 240, 16, 18))
        self.lck_Odor.setText("")
        self.lck_Odor.setObjectName("lck_Odor")
        self.btn_rr_Odor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Odor.setGeometry(QtCore.QRect(10, 240, 71, 21))
        self.btn_rr_Odor.setObjectName("btn_rr_Odor")
        self.lbl_Features = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Features.setGeometry(QtCore.QRect(70, 320, 71, 16))
        self.lbl_Features.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Features.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Features.setObjectName("lbl_Features")
        self.txt_Feature_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_1.setGeometry(QtCore.QRect(50, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_1.sizePolicy().hasHeightForWidth())
        self.txt_Feature_1.setSizePolicy(sizePolicy)
        self.txt_Feature_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_1.setObjectName("txt_Feature_1")
        self.btn_rr_Feature = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Feature.setGeometry(QtCore.QRect(70, 290, 71, 21))
        self.btn_rr_Feature.setObjectName("btn_rr_Feature")
        self.txt_Feature_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_2.setGeometry(QtCore.QRect(50, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_2.sizePolicy().hasHeightForWidth())
        self.txt_Feature_2.setSizePolicy(sizePolicy)
        self.txt_Feature_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_2.setObjectName("txt_Feature_2")
        self.txt_Feature_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_3.setGeometry(QtCore.QRect(50, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_3.sizePolicy().hasHeightForWidth())
        self.txt_Feature_3.setSizePolicy(sizePolicy)
        self.txt_Feature_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_3.setObjectName("txt_Feature_3")
        self.lck_Feature_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_1.setGeometry(QtCore.QRect(20, 340, 16, 18))
        self.lck_Feature_1.setText("")
        self.lck_Feature_1.setObjectName("lck_Feature_1")
        self.lck_Feature_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_2.setGeometry(QtCore.QRect(20, 370, 16, 18))
        self.lck_Feature_2.setText("")
        self.lck_Feature_2.setObjectName("lck_Feature_2")
        self.lck_Feature_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_3.setGeometry(QtCore.QRect(20, 400, 16, 18))
        self.lck_Feature_3.setText("")
        self.lck_Feature_3.setObjectName("lck_Feature_3")
        self.lbl_Locked_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Locked_2.setGeometry(QtCore.QRect(4, 320, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked_2.setFont(font)
        self.lbl_Locked_2.setObjectName("lbl_Locked_2")
        self.txt_Furnish_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_3.setGeometry(QtCore.QRect(50, 540, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_3.setObjectName("txt_Furnish_3")
        self.txt_Furnish_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_1.setGeometry(QtCore.QRect(50, 480, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_1.setObjectName("txt_Furnish_1")
        self.txt_Furnish_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_2.setGeometry(QtCore.QRect(50, 510, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_2.setObjectName("txt_Furnish_2")
        self.lbl_Furnish = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Furnish.setGeometry(QtCore.QRect(70, 460, 71, 16))
        self.lbl_Furnish.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish.setObjectName("lbl_Furnish")
        self.lck_Furnish_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_1.setGeometry(QtCore.QRect(20, 480, 16, 18))
        self.lck_Furnish_1.setText("")
        self.lck_Furnish_1.setObjectName("lck_Furnish_1")
        self.btn_rr_Furnish = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Furnish.setGeometry(QtCore.QRect(70, 430, 71, 21))
        self.btn_rr_Furnish.setObjectName("btn_rr_Furnish")
        self.lck_Furnish_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_3.setGeometry(QtCore.QRect(20, 540, 16, 18))
        self.lck_Furnish_3.setText("")
        self.lck_Furnish_3.setObjectName("lck_Furnish_3")
        self.lck_Furnish_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_2.setGeometry(QtCore.QRect(20, 510, 16, 18))
        self.lck_Furnish_2.setText("")
        self.lck_Furnish_2.setObjectName("lck_Furnish_2")
        self.txt_Furnish_Utensil_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Utensil_3.setGeometry(QtCore.QRect(220, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_3.setObjectName("txt_Furnish_Utensil_3")
        self.txt_Furnish_Utensil_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Utensil_1.setGeometry(QtCore.QRect(220, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_1.setObjectName("txt_Furnish_Utensil_1")
        self.lbl_Furnish_Utensil = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Furnish_Utensil.setGeometry(QtCore.QRect(230, 320, 101, 16))
        self.lbl_Furnish_Utensil.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Utensil.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Utensil.setObjectName("lbl_Furnish_Utensil")
        self.txt_Furnish_Utensil_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Utensil_2.setGeometry(QtCore.QRect(220, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Utensil_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Utensil_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Utensil_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Utensil_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Utensil_2.setObjectName("txt_Furnish_Utensil_2")
        self.lck_Furnish_Utensil_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Utensil_1.setGeometry(QtCore.QRect(190, 340, 16, 18))
        self.lck_Furnish_Utensil_1.setText("")
        self.lck_Furnish_Utensil_1.setObjectName("lck_Furnish_Utensil_1")
        self.lck_Furnish_Utensil_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Utensil_2.setGeometry(QtCore.QRect(190, 370, 16, 18))
        self.lck_Furnish_Utensil_2.setText("")
        self.lck_Furnish_Utensil_2.setObjectName("lck_Furnish_Utensil_2")
        self.lck_Furnish_Utensil_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Utensil_3.setGeometry(QtCore.QRect(190, 400, 16, 18))
        self.lck_Furnish_Utensil_3.setText("")
        self.lck_Furnish_Utensil_3.setObjectName("lck_Furnish_Utensil_3")
        self.btn_rr_Furnish_Utensil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Furnish_Utensil.setGeometry(QtCore.QRect(240, 290, 71, 21))
        self.btn_rr_Furnish_Utensil.setObjectName("btn_rr_Furnish_Utensil")
        self.txt_Book_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Book_3.setGeometry(QtCore.QRect(390, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_3.sizePolicy().hasHeightForWidth())
        self.txt_Book_3.setSizePolicy(sizePolicy)
        self.txt_Book_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_3.setObjectName("txt_Book_3")
        self.txt_Book_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Book_1.setGeometry(QtCore.QRect(390, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_1.sizePolicy().hasHeightForWidth())
        self.txt_Book_1.setSizePolicy(sizePolicy)
        self.txt_Book_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_1.setObjectName("txt_Book_1")
        self.lbl_Book = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Book.setGeometry(QtCore.QRect(410, 320, 71, 16))
        self.lbl_Book.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Book.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Book.setObjectName("lbl_Book")
        self.txt_Book_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Book_2.setGeometry(QtCore.QRect(390, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Book_2.sizePolicy().hasHeightForWidth())
        self.txt_Book_2.setSizePolicy(sizePolicy)
        self.txt_Book_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Book_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Book_2.setObjectName("txt_Book_2")
        self.lck_Book_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Book_1.setGeometry(QtCore.QRect(360, 340, 16, 18))
        self.lck_Book_1.setText("")
        self.lck_Book_1.setObjectName("lck_Book_1")
        self.lck_Book_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Book_2.setGeometry(QtCore.QRect(360, 370, 16, 18))
        self.lck_Book_2.setText("")
        self.lck_Book_2.setObjectName("lck_Book_2")
        self.lck_Book_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Book_3.setGeometry(QtCore.QRect(360, 400, 16, 18))
        self.lck_Book_3.setText("")
        self.lck_Book_3.setObjectName("lck_Book_3")
        self.btn_rr_Book = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Book.setGeometry(QtCore.QRect(410, 290, 71, 21))
        self.btn_rr_Book.setObjectName("btn_rr_Book")
        self.lck_Container_Contents_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Container_Contents_2.setGeometry(QtCore.QRect(530, 370, 16, 18))
        self.lck_Container_Contents_2.setText("")
        self.lck_Container_Contents_2.setObjectName("lck_Container_Contents_2")
        self.txt_Container_Contents_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Container_Contents_1.setGeometry(QtCore.QRect(560, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_1.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_1.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_1.setObjectName("txt_Container_Contents_1")
        self.txt_Container_Contents_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Container_Contents_2.setGeometry(QtCore.QRect(560, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_2.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_2.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_2.setObjectName("txt_Container_Contents_2")
        self.lck_Container_Contents_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Container_Contents_3.setGeometry(QtCore.QRect(530, 400, 16, 18))
        self.lck_Container_Contents_3.setText("")
        self.lck_Container_Contents_3.setObjectName("lck_Container_Contents_3")
        self.btn_rr_Container_Contents = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Container_Contents.setGeometry(QtCore.QRect(580, 290, 71, 21))
        self.btn_rr_Container_Contents.setObjectName("btn_rr_Container_Contents")
        self.lbl_Container_Contents = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Container_Contents.setGeometry(QtCore.QRect(570, 320, 101, 16))
        self.lbl_Container_Contents.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Container_Contents.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Container_Contents.setObjectName("lbl_Container_Contents")
        self.txt_Container_Contents_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Container_Contents_3.setGeometry(QtCore.QRect(560, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Container_Contents_3.sizePolicy().hasHeightForWidth())
        self.txt_Container_Contents_3.setSizePolicy(sizePolicy)
        self.txt_Container_Contents_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Container_Contents_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Container_Contents_3.setObjectName("txt_Container_Contents_3")
        self.lck_Container_Contents_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Container_Contents_1.setGeometry(QtCore.QRect(530, 340, 16, 18))
        self.lck_Container_Contents_1.setText("")
        self.lck_Container_Contents_1.setObjectName("lck_Container_Contents_1")
        self.lck_Furnish_Mage_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Mage_1.setGeometry(QtCore.QRect(190, 480, 16, 18))
        self.lck_Furnish_Mage_1.setText("")
        self.lck_Furnish_Mage_1.setObjectName("lck_Furnish_Mage_1")
        self.txt_Furnish_Mage_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Mage_1.setGeometry(QtCore.QRect(220, 480, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_1.setObjectName("txt_Furnish_Mage_1")
        self.lck_Furnish_Mage_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Mage_2.setGeometry(QtCore.QRect(190, 510, 16, 18))
        self.lck_Furnish_Mage_2.setText("")
        self.lck_Furnish_Mage_2.setObjectName("lck_Furnish_Mage_2")
        self.lbl_Furnish_Mage = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Furnish_Mage.setGeometry(QtCore.QRect(230, 460, 101, 16))
        self.lbl_Furnish_Mage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Mage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Mage.setObjectName("lbl_Furnish_Mage")
        self.lck_Furnish_Mage_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Mage_3.setGeometry(QtCore.QRect(190, 540, 16, 18))
        self.lck_Furnish_Mage_3.setText("")
        self.lck_Furnish_Mage_3.setObjectName("lck_Furnish_Mage_3")
        self.txt_Furnish_Mage_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Mage_2.setGeometry(QtCore.QRect(220, 510, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_2.setObjectName("txt_Furnish_Mage_2")
        self.btn_rr_Furnish_Mage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Furnish_Mage.setGeometry(QtCore.QRect(240, 430, 71, 21))
        self.btn_rr_Furnish_Mage.setObjectName("btn_rr_Furnish_Mage")
        self.txt_Furnish_Mage_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Mage_3.setGeometry(QtCore.QRect(220, 540, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Mage_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Mage_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Mage_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Mage_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Mage_3.setObjectName("txt_Furnish_Mage_3")
        self.lck_Furnish_Religous_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Religous_1.setGeometry(QtCore.QRect(360, 480, 16, 18))
        self.lck_Furnish_Religous_1.setText("")
        self.lck_Furnish_Religous_1.setObjectName("lck_Furnish_Religous_1")
        self.txt_Furnish_Religous_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Religous_3.setGeometry(QtCore.QRect(390, 540, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_3.setObjectName("txt_Furnish_Religous_3")
        self.lck_Furnish_Religous_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Religous_3.setGeometry(QtCore.QRect(360, 540, 16, 18))
        self.lck_Furnish_Religous_3.setText("")
        self.lck_Furnish_Religous_3.setObjectName("lck_Furnish_Religous_3")
        self.lck_Furnish_Religous_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_Religous_2.setGeometry(QtCore.QRect(360, 510, 16, 18))
        self.lck_Furnish_Religous_2.setText("")
        self.lck_Furnish_Religous_2.setObjectName("lck_Furnish_Religous_2")
        self.btn_rr_Furnish_Religous = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Furnish_Religous.setGeometry(QtCore.QRect(410, 430, 71, 21))
        self.btn_rr_Furnish_Religous.setObjectName("btn_rr_Furnish_Religous")
        self.txt_Furnish_Religous_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Religous_1.setGeometry(QtCore.QRect(390, 480, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_1.setObjectName("txt_Furnish_Religous_1")
        self.txt_Furnish_Religous_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_Religous_2.setGeometry(QtCore.QRect(390, 510, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_Religous_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_Religous_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_Religous_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_Religous_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_Religous_2.setObjectName("txt_Furnish_Religous_2")
        self.lbl_Furnish_Religous = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Furnish_Religous.setGeometry(QtCore.QRect(400, 460, 101, 16))
        self.lbl_Furnish_Religous.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish_Religous.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish_Religous.setObjectName("lbl_Furnish_Religous")
        self.box_chambers = QtWidgets.QGroupBox(self.centralwidget)
        self.box_chambers.setGeometry(QtCore.QRect(710, 40, 271, 161))
        self.box_chambers.setObjectName("box_chambers")
        self.btn_gen_chamber = QtWidgets.QPushButton(self.box_chambers)
        self.btn_gen_chamber.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.btn_gen_chamber.setObjectName("btn_gen_chamber")
        self.box_passages = QtWidgets.QGroupBox(self.centralwidget)
        self.box_passages.setGeometry(QtCore.QRect(720, 280, 251, 181))
        self.box_passages.setObjectName("box_passages")
        self.btn_gen_passage = QtWidgets.QPushButton(self.box_passages)
        self.btn_gen_passage.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.btn_gen_passage.setObjectName("btn_gen_passage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuGenerators = QtWidgets.QMenu(self.menubar)
        self.menuGenerators.setObjectName("menuGenerators")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChamber = QtWidgets.QAction(MainWindow)
        self.actionChamber.setObjectName("actionChamber")
        self.actionPassage = QtWidgets.QAction(MainWindow)
        self.actionPassage.setObjectName("actionPassage")
        self.actionDoor = QtWidgets.QAction(MainWindow)
        self.actionDoor.setObjectName("actionDoor")
        self.actionEntrance = QtWidgets.QAction(MainWindow)
        self.actionEntrance.setObjectName("actionEntrance")
        self.actionMonster = QtWidgets.QAction(MainWindow)
        self.actionMonster.setObjectName("actionMonster")
        self.actionNPC = QtWidgets.QAction(MainWindow)
        self.actionNPC.setObjectName("actionNPC")
        self.actionPlayer = QtWidgets.QAction(MainWindow)
        self.actionPlayer.setObjectName("actionPlayer")
        self.actionCity = QtWidgets.QAction(MainWindow)
        self.actionCity.setObjectName("actionCity")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionRoll_Tables = QtWidgets.QAction(MainWindow)
        self.actionRoll_Tables.setObjectName("actionRoll_Tables")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuEdit.addAction(self.actionRoll_Tables)
        self.menuGenerators.addAction(self.actionChamber)
        self.menuGenerators.addAction(self.actionPassage)
        self.menuGenerators.addAction(self.actionDoor)
        self.menuGenerators.addAction(self.actionEntrance)
        self.menuGenerators.addSeparator()
        self.menuGenerators.addAction(self.actionMonster)
        self.menuGenerators.addAction(self.actionNPC)
        self.menuGenerators.addAction(self.actionPlayer)
        self.menuGenerators.addSeparator()
        self.menuGenerators.addAction(self.actionCity)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuGenerators.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Random Session Maker"))
        self.lbl_Header.setText(_translate("MainWindow", "Welcome to the RPG Random Session Maker!"))
        self.btn_all_rr.setText(_translate("MainWindow", "Generate Starting Area"))
        self.lbl_DungeonType.setText(_translate("MainWindow", "Type:"))
        self.lbl_Locked.setText(_translate("MainWindow", "Locked"))
        self.lbl_Environment.setText(_translate("MainWindow", "Environment:"))
        self.lbl_StartArea.setText(_translate("MainWindow", "Starting Area:"))
        self.btn_rr_DungeonType.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Environment.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_StartArea.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Noise.setText(_translate("MainWindow", "Noise:"))
        self.btn_rr_Noise.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Air.setText(_translate("MainWindow", "Air:"))
        self.btn_rr_Air.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Odor.setText(_translate("MainWindow", "Odor:"))
        self.btn_rr_Odor.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Features.setText(_translate("MainWindow", "Features:"))
        self.btn_rr_Feature.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Locked_2.setText(_translate("MainWindow", "Locked"))
        self.lbl_Furnish.setText(_translate("MainWindow", "Furnishings:"))
        self.btn_rr_Furnish.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Furnish_Utensil.setText(_translate("MainWindow", "Utensils / Personal"))
        self.btn_rr_Furnish_Utensil.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Book.setText(_translate("MainWindow", "Books / Tomes"))
        self.btn_rr_Book.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Container_Contents.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Container_Contents.setText(_translate("MainWindow", "Container Contents"))
        self.lbl_Furnish_Mage.setText(_translate("MainWindow", "Furnishings: Mage"))
        self.btn_rr_Furnish_Mage.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Furnish_Religous.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Furnish_Religous.setText(_translate("MainWindow", "Furnishings: Relgious"))
        self.box_chambers.setTitle(_translate("MainWindow", "Chambers"))
        self.btn_gen_chamber.setText(_translate("MainWindow", "Generate Chamber"))
        self.box_passages.setTitle(_translate("MainWindow", "Passages"))
        self.btn_gen_passage.setText(_translate("MainWindow", "Generate Passage"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuGenerators.setTitle(_translate("MainWindow", "Generators"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionChamber.setText(_translate("MainWindow", "Chamber"))
        self.actionPassage.setText(_translate("MainWindow", "Passage"))
        self.actionDoor.setText(_translate("MainWindow", "Door"))
        self.actionEntrance.setText(_translate("MainWindow", "Entrance"))
        self.actionMonster.setText(_translate("MainWindow", "Monster"))
        self.actionNPC.setText(_translate("MainWindow", "NPC"))
        self.actionPlayer.setText(_translate("MainWindow", "Player"))
        self.actionCity.setText(_translate("MainWindow", "City"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionRoll_Tables.setText(_translate("MainWindow", "Roll Tables"))

import QtResources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

