# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSM_Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Header = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Header.setGeometry(QtCore.QRect(0, 0, 261, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Header.setFont(font)
        self.lbl_Header.setObjectName("lbl_Header")
        self.btn_all_rr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_all_rr.setGeometry(QtCore.QRect(20, 520, 131, 31))
        self.btn_all_rr.setObjectName("btn_all_rr")
        self.lbl_DungeonType = QtWidgets.QLabel(self.centralwidget)
        self.lbl_DungeonType.setGeometry(QtCore.QRect(170, 70, 31, 16))
        self.lbl_DungeonType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_DungeonType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_DungeonType.setObjectName("lbl_DungeonType")
        self.cb_DungeonType = QtWidgets.QComboBox(self.centralwidget)
        self.cb_DungeonType.setGeometry(QtCore.QRect(210, 70, 91, 22))
        self.cb_DungeonType.setObjectName("cb_DungeonType")
        self.lck_DungeonType = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_DungeonType.setGeometry(QtCore.QRect(100, 70, 16, 18))
        self.lck_DungeonType.setText("")
        self.lck_DungeonType.setObjectName("lck_DungeonType")
        self.lbl_Locked = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Locked.setGeometry(QtCore.QRect(90, 50, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked.setFont(font)
        self.lbl_Locked.setObjectName("lbl_Locked")
        self.lbl_Environment = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Environment.setGeometry(QtCore.QRect(140, 100, 71, 16))
        self.lbl_Environment.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Environment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Environment.setObjectName("lbl_Environment")
        self.lck_Environment = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Environment.setGeometry(QtCore.QRect(100, 100, 16, 18))
        self.lck_Environment.setText("")
        self.lck_Environment.setObjectName("lck_Environment")
        self.cb_Environment = QtWidgets.QComboBox(self.centralwidget)
        self.cb_Environment.setGeometry(QtCore.QRect(210, 100, 91, 22))
        self.cb_Environment.setObjectName("cb_Environment")
        self.lbl_StartArea = QtWidgets.QLabel(self.centralwidget)
        self.lbl_StartArea.setGeometry(QtCore.QRect(130, 140, 71, 16))
        self.lbl_StartArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_StartArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_StartArea.setObjectName("lbl_StartArea")
        self.lck_StartArea = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_StartArea.setGeometry(QtCore.QRect(100, 140, 16, 18))
        self.lck_StartArea.setText("")
        self.lck_StartArea.setObjectName("lck_StartArea")
        self.btn_rr_DungeonType = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_DungeonType.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.btn_rr_DungeonType.setObjectName("btn_rr_DungeonType")
        self.btn_rr_Environment = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Environment.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.btn_rr_Environment.setObjectName("btn_rr_Environment")
        self.btn_rr_StartArea = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_StartArea.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.btn_rr_StartArea.setObjectName("btn_rr_StartArea")
        self.txt_StartArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_StartArea.setGeometry(QtCore.QRect(210, 130, 391, 41))
        self.txt_StartArea.setObjectName("txt_StartArea")
        self.lbl_Noise = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Noise.setGeometry(QtCore.QRect(130, 180, 71, 16))
        self.lbl_Noise.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Noise.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Noise.setObjectName("lbl_Noise")
        self.btn_rr_Noise = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Noise.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.btn_rr_Noise.setObjectName("btn_rr_Noise")
        self.lck_Noise = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Noise.setGeometry(QtCore.QRect(100, 180, 16, 18))
        self.lck_Noise.setText("")
        self.lck_Noise.setObjectName("lck_Noise")
        self.txt_Noise = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Noise.setGeometry(QtCore.QRect(210, 180, 211, 21))
        self.txt_Noise.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Noise.setObjectName("txt_Noise")
        self.lbl_Air = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Air.setGeometry(QtCore.QRect(130, 210, 71, 16))
        self.lbl_Air.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Air.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Air.setObjectName("lbl_Air")
        self.btn_rr_Air = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Air.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.btn_rr_Air.setObjectName("btn_rr_Air")
        self.lck_Air = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Air.setGeometry(QtCore.QRect(100, 210, 16, 18))
        self.lck_Air.setText("")
        self.lck_Air.setObjectName("lck_Air")
        self.txt_Air = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Air.setGeometry(QtCore.QRect(210, 210, 211, 21))
        self.txt_Air.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Air.setObjectName("txt_Air")
        self.lbl_Odor = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Odor.setGeometry(QtCore.QRect(130, 240, 71, 16))
        self.lbl_Odor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Odor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Odor.setObjectName("lbl_Odor")
        self.txt_Odor = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Odor.setGeometry(QtCore.QRect(210, 240, 211, 21))
        self.txt_Odor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Odor.setObjectName("txt_Odor")
        self.lck_Odor = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Odor.setGeometry(QtCore.QRect(100, 240, 16, 18))
        self.lck_Odor.setText("")
        self.lck_Odor.setObjectName("lck_Odor")
        self.btn_rr_Odor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Odor.setGeometry(QtCore.QRect(10, 240, 71, 21))
        self.btn_rr_Odor.setObjectName("btn_rr_Odor")
        self.lbl_Features = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Features.setGeometry(QtCore.QRect(70, 320, 71, 16))
        self.lbl_Features.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Features.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Features.setObjectName("lbl_Features")
        self.txt_Feature_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_1.setGeometry(QtCore.QRect(50, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_1.sizePolicy().hasHeightForWidth())
        self.txt_Feature_1.setSizePolicy(sizePolicy)
        self.txt_Feature_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_1.setObjectName("txt_Feature_1")
        self.btn_rr_Feature = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Feature.setGeometry(QtCore.QRect(70, 290, 71, 21))
        self.btn_rr_Feature.setObjectName("btn_rr_Feature")
        self.txt_Feature_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_2.setGeometry(QtCore.QRect(50, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_2.sizePolicy().hasHeightForWidth())
        self.txt_Feature_2.setSizePolicy(sizePolicy)
        self.txt_Feature_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_2.setObjectName("txt_Feature_2")
        self.txt_Feature_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Feature_3.setGeometry(QtCore.QRect(50, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Feature_3.sizePolicy().hasHeightForWidth())
        self.txt_Feature_3.setSizePolicy(sizePolicy)
        self.txt_Feature_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Feature_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Feature_3.setObjectName("txt_Feature_3")
        self.lck_Feature_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_1.setGeometry(QtCore.QRect(20, 340, 16, 18))
        self.lck_Feature_1.setText("")
        self.lck_Feature_1.setObjectName("lck_Feature_1")
        self.lck_Feature_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_2.setGeometry(QtCore.QRect(20, 370, 16, 18))
        self.lck_Feature_2.setText("")
        self.lck_Feature_2.setObjectName("lck_Feature_2")
        self.lck_Feature_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Feature_3.setGeometry(QtCore.QRect(20, 400, 16, 18))
        self.lck_Feature_3.setText("")
        self.lck_Feature_3.setObjectName("lck_Feature_3")
        self.lbl_Locked_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Locked_2.setGeometry(QtCore.QRect(4, 320, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Locked_2.setFont(font)
        self.lbl_Locked_2.setObjectName("lbl_Locked_2")
        self.txt_Furnish_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_3.setGeometry(QtCore.QRect(240, 400, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_3.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_3.setSizePolicy(sizePolicy)
        self.txt_Furnish_3.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_3.setObjectName("txt_Furnish_3")
        self.txt_Furnish_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_1.setGeometry(QtCore.QRect(240, 340, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_1.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_1.setSizePolicy(sizePolicy)
        self.txt_Furnish_1.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_1.setObjectName("txt_Furnish_1")
        self.txt_Furnish_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Furnish_2.setGeometry(QtCore.QRect(240, 370, 121, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_Furnish_2.sizePolicy().hasHeightForWidth())
        self.txt_Furnish_2.setSizePolicy(sizePolicy)
        self.txt_Furnish_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txt_Furnish_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_Furnish_2.setObjectName("txt_Furnish_2")
        self.lbl_Furnish = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Furnish.setGeometry(QtCore.QRect(260, 320, 71, 16))
        self.lbl_Furnish.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_Furnish.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Furnish.setObjectName("lbl_Furnish")
        self.lck_Furnish_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_1.setGeometry(QtCore.QRect(210, 340, 16, 18))
        self.lck_Furnish_1.setText("")
        self.lck_Furnish_1.setObjectName("lck_Furnish_1")
        self.btn_rr_Furnish = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rr_Furnish.setGeometry(QtCore.QRect(260, 290, 71, 21))
        self.btn_rr_Furnish.setObjectName("btn_rr_Furnish")
        self.lck_Furnish_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_3.setGeometry(QtCore.QRect(210, 400, 16, 18))
        self.lck_Furnish_3.setText("")
        self.lck_Furnish_3.setObjectName("lck_Furnish_3")
        self.lck_Furnish_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.lck_Furnish_2.setGeometry(QtCore.QRect(210, 370, 16, 18))
        self.lck_Furnish_2.setText("")
        self.lck_Furnish_2.setObjectName("lck_Furnish_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuGenerators = QtWidgets.QMenu(self.menubar)
        self.menuGenerators.setObjectName("menuGenerators")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionChamber = QtWidgets.QAction(MainWindow)
        self.actionChamber.setObjectName("actionChamber")
        self.actionPassage = QtWidgets.QAction(MainWindow)
        self.actionPassage.setObjectName("actionPassage")
        self.actionDoor = QtWidgets.QAction(MainWindow)
        self.actionDoor.setObjectName("actionDoor")
        self.actionEntrance = QtWidgets.QAction(MainWindow)
        self.actionEntrance.setObjectName("actionEntrance")
        self.actionMonster = QtWidgets.QAction(MainWindow)
        self.actionMonster.setObjectName("actionMonster")
        self.actionNPC = QtWidgets.QAction(MainWindow)
        self.actionNPC.setObjectName("actionNPC")
        self.actionPlayer = QtWidgets.QAction(MainWindow)
        self.actionPlayer.setObjectName("actionPlayer")
        self.actionCity = QtWidgets.QAction(MainWindow)
        self.actionCity.setObjectName("actionCity")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionRoll_Tables = QtWidgets.QAction(MainWindow)
        self.actionRoll_Tables.setObjectName("actionRoll_Tables")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuEdit.addAction(self.actionRoll_Tables)
        self.menuGenerators.addAction(self.actionChamber)
        self.menuGenerators.addAction(self.actionPassage)
        self.menuGenerators.addAction(self.actionDoor)
        self.menuGenerators.addAction(self.actionEntrance)
        self.menuGenerators.addSeparator()
        self.menuGenerators.addAction(self.actionMonster)
        self.menuGenerators.addAction(self.actionNPC)
        self.menuGenerators.addAction(self.actionPlayer)
        self.menuGenerators.addSeparator()
        self.menuGenerators.addAction(self.actionCity)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuGenerators.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPG Random Session Maker"))
        self.lbl_Header.setText(_translate("MainWindow", "Welcome to the RPG Random Session Maker!"))
        self.btn_all_rr.setText(_translate("MainWindow", "Generate Starting Area"))
        self.lbl_DungeonType.setText(_translate("MainWindow", "Type:"))
        self.lbl_Locked.setText(_translate("MainWindow", "Locked"))
        self.lbl_Environment.setText(_translate("MainWindow", "Environment:"))
        self.lbl_StartArea.setText(_translate("MainWindow", "Starting Area:"))
        self.btn_rr_DungeonType.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_Environment.setText(_translate("MainWindow", "Re-Roll"))
        self.btn_rr_StartArea.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Noise.setText(_translate("MainWindow", "Noise:"))
        self.btn_rr_Noise.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Air.setText(_translate("MainWindow", "Air:"))
        self.btn_rr_Air.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Odor.setText(_translate("MainWindow", "Odor:"))
        self.btn_rr_Odor.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Features.setText(_translate("MainWindow", "Features:"))
        self.btn_rr_Feature.setText(_translate("MainWindow", "Re-Roll"))
        self.lbl_Locked_2.setText(_translate("MainWindow", "Locked"))
        self.lbl_Furnish.setText(_translate("MainWindow", "Furnishings:"))
        self.btn_rr_Furnish.setText(_translate("MainWindow", "Re-Roll"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuGenerators.setTitle(_translate("MainWindow", "Generators"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionChamber.setText(_translate("MainWindow", "Chamber"))
        self.actionPassage.setText(_translate("MainWindow", "Passage"))
        self.actionDoor.setText(_translate("MainWindow", "Door"))
        self.actionEntrance.setText(_translate("MainWindow", "Entrance"))
        self.actionMonster.setText(_translate("MainWindow", "Monster"))
        self.actionNPC.setText(_translate("MainWindow", "NPC"))
        self.actionPlayer.setText(_translate("MainWindow", "Player"))
        self.actionCity.setText(_translate("MainWindow", "City"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionRoll_Tables.setText(_translate("MainWindow", "Roll Tables"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

